In [1]:
import numpy as np

In [2]:
#Creamos un arreglo
r=np.array([0,0,10])
r

array([ 0,  0, 10])

In [3]:
#Chequeamos su dimensión mediante la instrucción '.ndim'
r.ndim

#El número obtenido refleja la cantidad de etiquetas que debo 
#utilizar para indexar dicho arreglo, o el número de índices
#requerido para identificar cada valor dentro del arreglo

1

Los componentes vectoriales se pueden representar mediante un único índice.

El vector:
$
v=(3,5,9)
$
Sus componentes:
$
v_i
$
donde
$
v_1=3,
$
$
v_2=5
$
y
$
v_3=9
$
.

Vamos a crear la siguiente matriz

$
\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{pmatrix}
$

In [4]:
m_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
m_1.ndim

2

In [6]:
#La instrucción '.shape' nos da la cantidad de valores que
#puede tomar cada índice

m_1.shape

(3, 3)

In [7]:
m_2=np.array([[1,2,3],[4,5,6]])
m_2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(m_2.ndim)
print(m_2.shape)

2
(2, 3)


In [9]:
#También podemos calcular el número total de elementos en un array
#mediante la instrucción '.size'
print(m_1.size)
print(m_2.size)

9
6


In [10]:
m_3=np.array([[1,2,3.5],[12.7,5,6]])
m_3

array([[ 1. ,  2. ,  3.5],
       [12.7,  5. ,  6. ]])

In [11]:
print(m_1)
print(m_1.dtype)
print('\n',m_2)
print(m_2.dtype)
print('\n',m_3)
print(m_3.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64

 [[1 2 3]
 [4 5 6]]
int64

 [[ 1.   2.   3.5]
 [12.7  5.   6. ]]
float64


In [12]:
#No podemos combinar valores numéricos y strings
m_4=np.array([[1,'2',3.5],[12.7,5,6]])
m_4

array([['1', '2', '3.5'],
       ['12.7', '5', '6']], dtype='<U21')

In [13]:
m_4.dtype

dtype('<U21')

In [14]:
#Podemos calcular el espacio en memoria en bytes
m_2.itemsize

8

In [15]:
#La ubicación en la memoria
m_3.data